// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs4DWkOX7i8l-mbpEFHbqaxTbj4jClNGg',
    appId: '1:932883739054:web:b10c12c756bbfb3215183f',
    messagingSenderId: '932883739054',
    projectId: 'fruit-hub-4dda6',
    authDomain: 'fruit-hub-4dda6.firebaseapp.com',
    storageBucket: 'fruit-hub-4dda6.appspot.com',
    measurementId: 'G-3WJWD0KBZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY_uwxv43Iz6VMozZ5NXWVLLDbjpIFDwo',
    appId: '1:932883739054:android:aa2dfc4e38e165ee15183f',
    messagingSenderId: '932883739054',
    projectId: 'fruit-hub-4dda6',
    storageBucket: 'fruit-hub-4dda6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHsDsPBPjNSGdqP_F3HPCjar4PANfWtHk',
    appId: '1:932883739054:ios:e10402294536d07f15183f',
    messagingSenderId: '932883739054',
    projectId: 'fruit-hub-4dda6',
    storageBucket: 'fruit-hub-4dda6.appspot.com',
    iosBundleId: 'com.example.fruitHub',
  );
}
